/* Посадкові сторінки під пошукові запити (ES). Список і логіка — docs/ES_LANDINGS_20_zapyty.md
   price: ключ з PRICES у src/data.mjs або null («bajo presupuesto»).
   img / gallery: якщо не задано — lp-<slug>.jpg і lp-<slug>-1..3.jpg (заглушки, доки немає фото). */

export const common = {
  home: 'Inicio',
  label: { why: 'Por qué con nosotros', specs: 'Detalles técnicos', gallery: 'Trabajos', process: 'Cómo trabajamos', faq: 'Preguntas', related: 'También te puede interesar' },
  specsH2: ['Lo que', 'conviene saber'],
  galleryH2: ['Del taller', 'a tu casa'],
  processH2: ['Cuatro pasos,', 'un responsable'],
  faqH2: ['Preguntas', 'frecuentes'],
  relatedH2: ['Otros trabajos', 'en piedra'],
  cta: 'Pedir presupuesto',
  whatsapp: 'WhatsApp',
  area: 'Alicante, Elche, Novelda, Benidorm, Torrevieja, Jávea y toda la Costa Blanca',
  steps: [
    { t: 'Medición', d: 'Medimos en tu casa con láser o plantilla.' },
    { t: 'Diseño', d: 'Plano técnico y elección de la placa contigo.' },
    { t: 'Fabricación', d: 'Corte, CNC y pulido en nuestro taller de Novelda.' },
    { t: 'Instalación', d: 'Nuestro equipo monta, sella y limpia.' },
  ],
  contact: {
    label: 'Contacto',
    h2: ['Pide tu', 'presupuesto'],
    intro: 'Mándanos medidas aproximadas o una foto. Te respondemos con un precio orientativo en 24 horas.',
  },
  more: 'Ver',
  back: 'Todos los productos',
};

export const pages = [
  {
    slug: 'encimeras-de-cuarzo', chip: 'kitchen', price: 'kitchen',
    title: 'Encimeras de cuarzo a medida en Alicante | ESTONE',
    description: 'Encimeras de cuarzo para cocina y baño fabricadas a medida en nuestro taller de Novelda. Medición, fregadero integrado e instalación en la Costa Blanca.',
    h1: ['Encimeras', 'de cuarzo'],
    sub: 'A medida, con fregadero y frontal a juego. Fabricadas en Novelda e instaladas por nuestro equipo.',
    intro: 'El cuarzo es la encimera más pedida en cocina por una razón práctica: no absorbe líquidos, resiste manchas de vino, aceite o café y no necesita sellado. Cortamos cada encimera de cuarzo según la medición real de tu cocina, con huecos para placa y fregadero, cantos a elegir y frontal del mismo color. Trabajamos con placas de 12, 20 y 30 mm en acabado pulido, mate o texturizado, y con una amplia carta de colores: blancos lisos, grises, efecto mármol y tonos cálidos.',
    benefits: [
      { t: 'No absorbe', d: 'Superficie no porosa: no hay que sellarla y es higiénica para la cocina.' },
      { t: 'Resiste el uso diario', d: 'Aguanta arañazos y manchas mejor que la piedra natural.' },
      { t: 'Color uniforme', d: 'Frontal, peto y encimera del mismo tono, sin sorpresas entre placas.' },
      { t: 'Instalación propia', d: 'Medimos, fabricamos y montamos nosotros: un solo responsable.' },
    ],
    specs: [
      ['Grosores', '12 · 20 · 30 mm'],
      ['Tamaño de placa', 'hasta 3200 × 1600 mm'],
      ['Acabados', 'pulido, mate, texturizado'],
      ['Cantos', 'recto, biselado, redondeado, inglete'],
      ['Uso exterior', 'no recomendado (sensible a UV)'],
    ],
    faq: [
      { q: '¿Cuánto cuesta una encimera de cuarzo?', a: 'Depende del color, el grosor y los huecos. Con las medidas aproximadas te damos un precio en 24 horas; la medición en casa no tiene coste si aceptas el presupuesto.' },
      { q: '¿Se puede apoyar una olla caliente sobre el cuarzo?', a: 'Mejor no. El cuarzo resiste el calor moderado, pero un cambio brusco de temperatura puede marcarlo. Si cocinas mucho, valora el porcelánico.' },
      { q: '¿Hacéis también el frontal de cuarzo?', a: 'Sí. Frontal, peto, alféizar y encimera salen de las mismas placas para que el color coincida.' },
    ],
    related: ['encimeras-porcelanicas', 'islas-de-cocina', 'fregaderos-de-piedra'],
  },
  {
    slug: 'encimeras-de-cocina-a-medida', chip: 'kitchen', price: 'kitchen',
    title: 'Encimeras de cocina a medida en Alicante | Taller en Novelda',
    description: 'Encimeras de cocina a medida en cuarzo, porcelánico, granito y mármol. Medimos tu cocina, fabricamos en Novelda e instalamos en toda la Costa Blanca.',
    h1: ['Encimeras de cocina', 'a medida'],
    sub: 'Cuarzo, porcelánico, granito o mármol. Te ayudamos a elegir según cómo usas tu cocina.',
    intro: 'Una encimera de cocina a medida empieza con la cocina ya montada: medimos los muebles reales, no el plano, para que la encimera encaje sin cortes en obra. Después eliges material y color con nosotros, en el taller o con muestras. Fabricamos en Novelda la encimera, los huecos de placa y fregadero, el frontal y los alféizares a juego, y la instalamos con nuestro propio equipo. Trabajamos en cocinas nuevas y en reformas, con L, U, península o isla.',
    benefits: [
      { t: 'Cuatro materiales', d: 'Cuarzo, porcelánico, granito y mármol: te explicamos cuál conviene.' },
      { t: 'Medición real', d: 'Sobre los muebles montados, con láser o plantilla.' },
      { t: 'Todo a juego', d: 'Frontal, peto, alféizar y encimera del mismo material.' },
      { t: 'Plazo cerrado', d: 'Te damos la fecha de instalación antes de empezar.' },
    ],
    specs: [
      ['Materiales', 'cuarzo, porcelánico, granito, mármol'],
      ['Grosores', 'de 12 a 40 mm'],
      ['Formas', 'recta, L, U, península, isla'],
      ['Huecos', 'placa, fregadero bajo encimera, enchufes'],
      ['Zona', 'Alicante, Murcia y Valencia bajo consulta'],
    ],
    faq: [
      { q: '¿Qué material es mejor para la encimera de cocina?', a: 'Para uso intensivo y sin mantenimiento, cuarzo o porcelánico. Si cocinas con mucho calor, porcelánico. Si buscas una pieza única con veta natural, mármol o granito.' },
      { q: '¿Cuándo hay que medir la encimera?', a: 'Con los muebles bajos ya instalados y nivelados. Así la encimera encaja al milímetro.' },
      { q: '¿Retiráis la encimera vieja?', a: 'Sí, en reformas desmontamos y retiramos la encimera antigua el mismo día de la instalación.' },
    ],
    related: ['encimeras-de-cuarzo', 'encimeras-de-granito', 'islas-de-cocina'],
  },
  {
    slug: 'encimeras-porcelanicas', chip: 'kitchen', price: 'kitchen',
    title: 'Encimeras porcelánicas y de piedra sinterizada a medida | ESTONE',
    description: 'Encimeras porcelánicas a medida: resisten el calor, los arañazos y el sol. Placas de 12 y 20 mm, fregadero integrado e instalación en Alicante.',
    h1: ['Encimeras', 'porcelánicas'],
    sub: 'Porcelánico y piedra sinterizada: la encimera que aguanta calor, sol y uso intensivo.',
    intro: 'La encimera porcelánica se fabrica con placas de gran formato cocidas a más de 1200 °C. El resultado es una superficie que aguanta una sartén caliente, no se raya con el cuchillo y no pierde color al sol, por eso también sirve para cocinas de exterior y barbacoas. Es un material duro y delicado de cortar: lo trabajamos con CNC y chorro de agua en nuestro taller de Novelda, con ingletes a 45° para que el canto parezca macizo y fregaderos integrados del mismo material.',
    benefits: [
      { t: 'Resiste el calor', d: 'Puedes apoyar ollas y sartenes calientes sin marcas.' },
      { t: 'Apto para exterior', d: 'No se decolora con el sol: ideal para terrazas y barbacoas.' },
      { t: 'Canto en inglete', d: 'Unión a 45° que da aspecto de bloque macizo.' },
      { t: 'Corte de precisión', d: 'CNC y waterjet propios para huecos y formas limpias.' },
    ],
    specs: [
      ['Grosores', '6 · 12 · 20 mm'],
      ['Tamaño de placa', 'hasta 3200 × 1600 mm'],
      ['Acabados', 'mate, pulido, satinado, texturizado'],
      ['Canto', 'inglete 45°, recto pulido'],
      ['Uso exterior', 'sí'],
    ],
    faq: [
      { q: '¿Porcelánico o cuarzo?', a: 'El porcelánico aguanta mejor el calor y el sol; el cuarzo es algo más tolerante a golpes en los cantos. Te enseñamos ambos en el taller.' },
      { q: '¿Se puede integrar el fregadero en porcelánico?', a: 'Sí. Fabricamos el seno con piezas del mismo porcelánico y lo montamos bajo encimera o integrado.' },
      { q: '¿Es lo mismo porcelánico que piedra sinterizada?', a: 'Son materiales muy parecidos: ambos se fabrican a alta presión y temperatura. Cambian la composición y el fabricante; el resultado en cocina es similar.' },
    ],
    related: ['encimeras-de-cuarzo', 'mesas-de-porcelanico', 'porcelanico-gran-formato'],
  },
  {
    slug: 'encimeras-de-granito', chip: 'kitchen', price: 'kitchen',
    title: 'Encimeras de granito a medida en Alicante | ESTONE',
    description: 'Encimeras de granito natural para cocina y exterior, cortadas a medida en Novelda. Pulido, apomazado o flameado. Medición e instalación en la Costa Blanca.',
    h1: ['Encimeras', 'de granito'],
    sub: 'Piedra natural dura y resistente, para cocinas interiores y de exterior.',
    intro: 'El granito es una de las piedras naturales más duras: soporta el calor, los golpes y el uso diario, y dura décadas. Cada placa tiene su propio dibujo, por eso te invitamos a elegirla en persona antes de cortarla. Fabricamos encimeras de granito a medida para cocina, barbacoa y lavadero, con acabado pulido, apomazado mate o flameado antideslizante para exterior. Sellamos la superficie al instalarla para que resista mejor las manchas.',
    benefits: [
      { t: 'Muy duro', d: 'Resiste calor, golpes y arañazos del día a día.' },
      { t: 'Placa única', d: 'Eliges tu placa en el taller antes del corte.' },
      { t: 'Interior y exterior', d: 'Acabados flameados para barbacoas y terrazas.' },
      { t: 'Precio contenido', d: 'Una piedra natural con muy buena relación calidad-precio.' },
    ],
    specs: [
      ['Grosores', '20 · 30 mm'],
      ['Acabados', 'pulido, apomazado, flameado, cepillado'],
      ['Tratamiento', 'sellado antimanchas al instalar'],
      ['Cantos', 'recto, biselado, media caña, doble canto'],
      ['Uso exterior', 'sí'],
    ],
    faq: [
      { q: '¿El granito se mancha?', a: 'Es poco poroso, pero conviene sellarlo. Lo dejamos sellado al instalar y te explicamos cómo mantenerlo.' },
      { q: '¿Puedo ver la placa antes de que la cortéis?', a: 'Sí, y lo recomendamos. Ven al taller de Novelda con cita y elige la placa que se usará.' },
      { q: '¿Sirve para una barbacoa exterior?', a: 'Sí. Para exterior usamos acabado flameado o cepillado, que no resbala y aguanta la intemperie.' },
    ],
    related: ['encimeras-de-marmol', 'encimeras-de-cocina-a-medida', 'escaleras-de-marmol'],
  },
  {
    slug: 'encimeras-de-marmol', chip: 'kitchen', price: 'kitchen',
    title: 'Encimeras de mármol a medida desde Novelda | ESTONE',
    description: 'Encimeras de mármol para cocina y baño seleccionadas y cortadas en Novelda, la capital del mármol. Placas únicas, acabado pulido o mate, instalación propia.',
    h1: ['Encimeras', 'de mármol'],
    sub: 'Placas seleccionadas en Novelda, la capital del mármol. Cada encimera es única.',
    intro: 'Una encimera de mármol no se parece a ninguna otra: la veta, el color y la profundidad cambian en cada bloque. En Novelda trabajamos rodeados de canteras y almacenes de mármol, así que te acompañamos a elegir la placa y a casar las vetas entre piezas. El mármol es más blando y poroso que el cuarzo, por eso lo sellamos al instalar y te recomendamos acabado mate si quieres que las marcas de uso se noten menos. Lo fabricamos para cocinas, baños, islas y mesas.',
    benefits: [
      { t: 'Veta continua', d: 'Casamos el dibujo entre encimera, frontal e isla.' },
      { t: 'Desde Novelda', d: 'Acceso directo a placas de mármol nacional e importado.' },
      { t: 'Acabado a elección', d: 'Pulido para brillo, mate o apomazado para uso diario.' },
      { t: 'Consejo honesto', d: 'Te explicamos dónde conviene mármol y dónde no.' },
    ],
    specs: [
      ['Grosores', '20 · 30 mm'],
      ['Acabados', 'pulido, apomazado, envejecido'],
      ['Tratamiento', 'sellado hidro-oleófugo'],
      ['Casado de vetas', 'libro abierto o continuo'],
      ['Mármoles', 'blancos, cremas, grises, verdes, negros'],
    ],
    faq: [
      { q: '¿El mármol es buena idea para la cocina?', a: 'Sí, si aceptas que envejece: con limón o vino puede marcarse. Con acabado mate y un buen sellado el desgaste se nota mucho menos.' },
      { q: '¿Qué es el casado en libro abierto?', a: 'Colocar dos placas consecutivas del mismo bloque como un espejo, para que la veta forme un dibujo simétrico.' },
      { q: '¿Trabajáis mármol que yo compre?', a: 'Sí, cortamos e instalamos placas que traigas tú. Revisamos antes su estado.' },
    ],
    related: ['mesas-de-marmol', 'lavabos-de-piedra', 'marmoleria-alicante'],
  },
  {
    slug: 'platos-de-ducha-a-medida', chip: 'bath', price: null,
    title: 'Platos de ducha a medida en piedra y solid surface | ESTONE',
    description: 'Platos de ducha a medida de piedra, porcelánico o solid surface, enrasados con el suelo y con desagüe lineal oculto. Fabricación en Novelda, Alicante.',
    h1: ['Platos de ducha', 'a medida'],
    sub: 'Enrasados con el suelo, del mismo material que el baño y con desagüe oculto.',
    intro: 'Un plato de ducha a medida ocupa exactamente el hueco de tu ducha, sin recortes ni juntas de silicona a la vista. Lo fabricamos en porcelánico, mármol, piedra natural o solid surface, con las pendientes fresadas por CNC hacia un desagüe lineal o de ranura oculta. Puede ir enrasado con el suelo para una ducha a ras, y a juego con el revestimiento de las paredes y la encimera del baño, para que todo parezca una sola pieza.',
    benefits: [
      { t: 'Al milímetro', d: 'Para huecos irregulares, en esquina o bajo buhardilla.' },
      { t: 'A ras de suelo', d: 'Sin escalón: accesible y más fácil de limpiar.' },
      { t: 'Desagüe oculto', d: 'Ranura lineal o rejilla del mismo material.' },
      { t: 'Antideslizante', d: 'Surcos fresados o acabado texturizado.' },
    ],
    specs: [
      ['Materiales', 'porcelánico, mármol, solid surface, granito'],
      ['Tamaño máximo', 'hasta 3000 × 1500 mm de una pieza'],
      ['Pendiente', 'fresada CNC hacia el desagüe'],
      ['Desagüe', 'lineal, ranura oculta, rejilla a juego'],
      ['Acabado', 'antideslizante clase 2–3'],
    ],
    faq: [
      { q: '¿Se puede poner un plato de ducha a ras de suelo en una reforma?', a: 'Normalmente sí, rebajando la solera. Lo revisamos en la medición y te decimos qué obra hace falta.' },
      { q: '¿Resbala un plato de ducha de piedra?', a: 'No con el acabado adecuado. Fresamos surcos o usamos superficies texturizadas antideslizantes.' },
      { q: '¿Podéis hacer paredes y plato del mismo material?', a: 'Sí, es lo que más recomendamos: plato, paredes y encimera del mismo porcelánico o mármol.' },
    ],
    related: ['lavabos-a-medida', 'porcelanico-gran-formato', 'lavabos-de-piedra'],
  },
  {
    slug: 'lavabos-de-piedra', chip: 'bath', price: 'bath',
    img: 'le-02.jpg', gallery: ['le-06.jpg', 'le-04.jpg', 'ka-06.jpg'],
    title: 'Lavabos de piedra natural y mármol a medida | ESTONE',
    description: 'Lavabos de piedra natural y mármol tallados a mano o por CNC: cuencos sobre encimera, pedestales y encimeras con lavabo. Colección Leonardo y piezas a medida.',
    h1: ['Lavabos', 'de piedra'],
    sub: 'Cuencos, pedestales y encimeras talladas en mármol y piedra natural. No hay dos iguales.',
    intro: 'Un lavabo de piedra natural es la pieza que define un baño. Tallamos cuencos a partir de un bloque de mármol, lavabos de pie sobre pedestal y encimeras con la cubeta vaciada en la misma piedra, sin juntas. Tú eliges la piedra y la forma; nosotros la modelamos en 3D, la tallamos con CNC y la terminamos a mano. Nuestra colección Leonardo reúne modelos que combinan mármol, vidrio y cuarzo, y todos se pueden adaptar a tus medidas.',
    benefits: [
      { t: 'De un solo bloque', d: 'Cuencos y cubetas talladas sin juntas ni pegados.' },
      { t: 'Piedra a elegir', d: 'Mármoles blancos, rojos, verdes, travertino, ónix.' },
      { t: 'Colección propia', d: 'Serie Leonardo, adaptable a tu baño.' },
      { t: 'Acabado protegido', d: 'Sellado para el uso diario con agua y jabón.' },
    ],
    specs: [
      ['Tipos', 'cuenco sobre encimera, pedestal, encimera con cubeta'],
      ['Materiales', 'mármol, travertino, ónix, granito'],
      ['Acabados', 'pulido, apomazado, envejecido'],
      ['Desagüe', 'válvula clic-clac o rebosadero oculto'],
      ['Fabricación', 'CNC 5 ejes + acabado a mano'],
    ],
    faq: [
      { q: '¿Un lavabo de mármol se mancha con el jabón?', a: 'Lo sellamos al fabricarlo. Con limpieza con jabón neutro y un sellado anual se mantiene muy bien.' },
      { q: '¿Puedo elegir la piedra de mi lavabo?', a: 'Sí. Te enseñamos bloques y placas en el taller o te mandamos fotos y muestras.' },
      { q: '¿Cuánto pesa un lavabo de piedra?', a: 'Un cuenco medio pesa entre 15 y 40 kg. Revisamos que la encimera o el mueble lo soporten.' },
    ],
    related: ['lavabos-a-medida', 'encimeras-de-marmol', 'esculturas-de-marmol'],
  },
  {
    slug: 'lavabos-a-medida', chip: 'bath', price: 'bath',
    img: 'ka-07.jpg', gallery: ['mo-01.jpg', 'sa-02.jpg', 'ka-05.jpg'],
    title: 'Lavabos a medida y encimeras de baño con lavabo integrado | ESTONE',
    description: 'Encimeras de baño con lavabo integrado sin juntas: solid surface, porcelánico y cuarzo. Desagüe de ranura oculto, dobles lavabos y formas a medida.',
    h1: ['Lavabos', 'a medida'],
    sub: 'Encimera y lavabo en una sola pieza, sin juntas donde se acumule la suciedad.',
    intro: 'Fabricamos encimeras de baño con el lavabo integrado en el mismo material: solid surface, porcelánico o cuarzo. Sin juntas ni silicona entre cubeta y encimera, el baño se limpia en segundos. Diseñamos cada pieza para tu hueco: lavabo simple o doble, cubeta ovalada, rectangular o con fondo inclinado y desagüe de ranura oculto, repisas y mueble revestido a juego. Nuestras colecciones Monet, Kazimir y Salvador son un punto de partida; las medidas las pones tú.',
    benefits: [
      { t: 'Sin juntas', d: 'La encimera se convierte en lavabo sin una sola unión.' },
      { t: 'Desagüe oculto', d: 'Ranura lineal: no se ve la válvula.' },
      { t: 'Doble lavabo', d: 'Con zona personal entre ambos senos.' },
      { t: 'Mueble a juego', d: 'Revestimos el mueble con el mismo material.' },
    ],
    specs: [
      ['Materiales', 'solid surface, porcelánico, cuarzo'],
      ['Largo máximo', 'hasta 3600 mm (solid surface sin juntas)'],
      ['Cubetas', 'oval, rectangular, inclinada, doble'],
      ['Desagüe', 'ranura oculta, clic-clac, rebosadero'],
      ['Colecciones', 'Monet, Kazimir, Salvador'],
    ],
    faq: [
      { q: '¿Qué es el solid surface?', a: 'Un material acrílico con minerales que se une sin juntas visibles, se puede curvar y se repara lijando.' },
      { q: '¿Se puede reparar un arañazo?', a: 'En solid surface sí, se lija y se pule en casa. En porcelánico y cuarzo los arañazos casi no aparecen.' },
      { q: '¿Hacéis también el mueble?', a: 'Revestimos muebles con el mismo material o colaboramos con tu carpintero para que encaje al milímetro.' },
    ],
    related: ['lavabos-de-piedra', 'platos-de-ducha-a-medida', 'encimeras-de-cuarzo'],
  },
  {
    slug: 'mesas-de-marmol', chip: 'furniture', price: 'furniture',
    title: 'Mesas de mármol a medida: comedor, centro y exterior | ESTONE',
    description: 'Mesas de mármol a medida para comedor, salón y exterior. Tableros de una sola placa, patas de piedra, metal o madera. Fabricadas en Novelda, Alicante.',
    h1: ['Mesas', 'de mármol'],
    sub: 'Tableros de una sola placa para comedor, salón y terraza, en la medida que necesitas.',
    intro: 'Una mesa de mármol es una pieza para toda la vida. Cortamos el tablero de una sola placa, elegida contigo por su veta, y lo terminamos con el canto que prefieras: recto, redondeado o biselado bajo. Las patas pueden ser de la misma piedra, en metal o en madera de tu carpintero. Fabricamos mesas de comedor, de centro, auxiliares y consolas, redondas, ovaladas o rectangulares, y mesas de exterior en piedras que aguantan el sol.',
    benefits: [
      { t: 'Una sola placa', d: 'Tableros sin juntas hasta más de 3 metros.' },
      { t: 'Cualquier forma', d: 'Redonda, oval, orgánica o rectangular.' },
      { t: 'Base a juego', d: 'Pedestal de piedra, metal o madera.' },
      { t: 'Protegida', d: 'Sellado antimanchas para uso diario.' },
    ],
    specs: [
      ['Tipos', 'comedor, centro, auxiliar, consola, exterior'],
      ['Grosor del tablero', '20 · 30 mm (canto visual hasta 60 mm)'],
      ['Medida máxima', 'aprox. 3000 × 1500 mm'],
      ['Acabados', 'pulido, apomazado, envejecido'],
      ['Bases', 'piedra maciza, acero, latón, madera'],
    ],
    faq: [
      { q: '¿Una mesa de mármol se mancha con vino?', a: 'Puede, si el líquido se deja mucho tiempo. La sellamos antes de entregarla y te damos pautas de mantenimiento sencillas.' },
      { q: '¿Cuánto pesa una mesa de comedor de mármol?', a: 'Un tablero de 200 × 100 cm en 20 mm pesa unos 110 kg. Lo entregamos y montamos nosotros.' },
      { q: '¿Hacéis mesas para restaurantes?', a: 'Sí, series de mesas y barras para hostelería con plazos fijos.' },
    ],
    related: ['mesas-de-porcelanico', 'encimeras-de-marmol', 'esculturas-de-marmol'],
  },
  {
    slug: 'mesas-de-porcelanico', chip: 'furniture', price: 'furniture',
    title: 'Mesas de porcelánico y cerámica a medida | Interior y exterior | ESTONE',
    description: 'Mesas de porcelánico y cerámica a medida para comedor, cocina y terraza. Resisten calor, rayas y sol. Tableros ligeros, cantos en inglete, base a elegir.',
    h1: ['Mesas', 'de porcelánico'],
    sub: 'La estética del mármol con la resistencia de la cerámica, dentro y fuera de casa.',
    intro: 'Las mesas de porcelánico se han hecho populares por una razón: tienen el aspecto de la piedra natural y aguantan casi todo. No se rayan, no se manchan, resisten una fuente caliente y pueden quedarse en la terraza todo el año. Fabricamos tableros con placa de 12 mm reforzada, canto en inglete que simula un grosor macizo y la base que prefieras. Hacemos mesas de comedor, de cocina, de centro y de exterior, a juego con la encimera si quieres.',
    benefits: [
      { t: 'Aguanta todo', d: 'Calor, arañazos, manchas y sol.' },
      { t: 'Más ligera', d: 'Tablero de 12 mm reforzado: más fácil de mover.' },
      { t: 'Canto macizo', d: 'Inglete a 45° con aspecto de bloque.' },
      { t: 'A juego', d: 'Con la encimera o el revestimiento de tu casa.' },
    ],
    specs: [
      ['Tipos', 'comedor, cocina, centro, exterior'],
      ['Tablero', 'porcelánico 12 mm reforzado'],
      ['Canto visual', '20 · 40 · 60 mm en inglete'],
      ['Acabados', 'mate, pulido, texturizado'],
      ['Uso exterior', 'sí'],
    ],
    faq: [
      { q: '¿Mesa de porcelánico o de mármol?', a: 'El porcelánico es más resistente y apto para exterior; el mármol es natural y único. Te enseñamos ambos en el taller.' },
      { q: '¿Se rompe el porcelánico con un golpe?', a: 'El tablero es muy duro, pero el canto puede astillarse con un golpe fuerte. Por eso reforzamos la placa y redondeamos ligeramente las aristas.' },
      { q: '¿Puedo tener la mesa a juego con mi encimera?', a: 'Sí, usamos el mismo modelo de placa para encimera, isla y mesa.' },
    ],
    related: ['mesas-de-marmol', 'encimeras-porcelanicas', 'islas-de-cocina'],
  },
  {
    slug: 'escaleras-de-marmol', chip: 'stairs', price: 'stairs',
    title: 'Escaleras de mármol y granito a medida: peldaños y zanquines | ESTONE',
    description: 'Escaleras de mármol, granito y porcelánico a medida: peldaños de una pieza, tabicas, zanquines, escaleras voladas y de caracol. Medición e instalación en Alicante.',
    h1: ['Escaleras', 'de mármol'],
    sub: 'Peldaños de una pieza cortados para su sitio, con antideslizante y luz integrada.',
    intro: 'En una escalera cada peldaño es distinto, aunque no lo parezca. Por eso medimos la escalera ya construida y cortamos cada huella y tabica para su posición exacta. Fabricamos escaleras de mármol, granito y porcelánico, interiores y exteriores: rectas, en L, de caracol y voladas empotradas en el muro. Añadimos ranuras antideslizantes, canto redondeado o recto y ranura para tira LED bajo el peldaño. El zanquín y el rodapié se cortan del mismo material.',
    benefits: [
      { t: 'Pieza a pieza', d: 'Cada peldaño se mide y se corta para su sitio.' },
      { t: 'Seguridad', d: 'Ranuras antideslizantes o acabado flameado.' },
      { t: 'Luz integrada', d: 'Ranura para LED bajo la huella.' },
      { t: 'Conjunto completo', d: 'Huella, tabica, zanquín y rodapié a juego.' },
    ],
    specs: [
      ['Materiales', 'mármol, granito, porcelánico'],
      ['Huella', '20 · 30 · 40 mm'],
      ['Tipos', 'recta, en L, caracol, volada'],
      ['Antideslizante', 'ranuras fresadas o flameado'],
      ['Extras', 'ranura LED, zanquín, rodapié'],
    ],
    faq: [
      { q: '¿Se puede revestir una escalera de hormigón existente?', a: 'Sí, es el caso más habitual. Medimos cada peldaño y fabricamos huellas y tabicas a medida.' },
      { q: '¿El mármol resbala en la escalera?', a: 'El pulido puede resbalar con agua. Recomendamos ranuras antideslizantes o acabado apomazado, y flameado en exterior.' },
      { q: '¿Cuánto tarda la instalación?', a: 'Una escalera de un piso suele montarse en uno o dos días.' },
    ],
    related: ['encimeras-de-granito', 'porcelanico-gran-formato', 'marmoleria-alicante'],
  },
  {
    slug: 'porcelanico-gran-formato', chip: 'cladding', price: 'cladding',
    title: 'Revestimiento de porcelánico gran formato a medida | ESTONE',
    description: 'Revestimiento de paredes, duchas y chimeneas con porcelánico gran formato de hasta 3,2 × 1,6 m. Cortado a medida, casi sin juntas, con veta continua.',
    h1: ['Porcelánico', 'gran formato'],
    sub: 'Paredes, duchas y chimeneas con placas XXL de hasta 3,2 × 1,6 m, casi sin juntas.',
    intro: 'El porcelánico de gran formato permite revestir una pared entera con dos o tres placas en lugar de cientos de azulejos. Menos juntas significa una superficie más limpia, más fácil de mantener y con la veta continua de una placa a otra. Cortamos cada placa a la medida exacta de la pared, con huecos para enchufes, grifería y hornacinas, y la colocamos con nuestro propio equipo. Lo usamos en baños completos, duchas, salones, chimeneas y cocinas.',
    benefits: [
      { t: 'Casi sin juntas', d: 'Una pared con 2 o 3 placas en vez de azulejos.' },
      { t: 'Veta continua', d: 'Casamos el dibujo entre placas contiguas.' },
      { t: 'Cortes exactos', d: 'Huecos y hornacinas por CNC y waterjet.' },
      { t: 'Colocación propia', d: 'Manipular placas XXL requiere equipo y experiencia.' },
    ],
    specs: [
      ['Formato máximo', '3200 × 1600 mm'],
      ['Grosores', '6 · 12 mm'],
      ['Usos', 'paredes, duchas, chimeneas, suelos, frentes'],
      ['Acabados', 'mate, pulido, efecto mármol, piedra, cemento'],
      ['Colocación', 'adhesivo C2S1, juntas mínimas'],
    ],
    faq: [
      { q: '¿Se puede poner porcelánico gran formato sobre azulejo viejo?', a: 'Muchas veces sí, si la pared está plana y firme. Lo comprobamos en la medición.' },
      { q: '¿Cómo entran placas de 3 metros en casa?', a: 'Planificamos el acceso antes. Si no caben por la escalera o el ascensor, cortamos en piezas casando la veta.' },
      { q: '¿Sirve para dentro de la ducha?', a: 'Sí, es impermeable. Combinado con un plato a medida del mismo material queda una ducha sin azulejos.' },
    ],
    related: ['fachadas-ventiladas', 'platos-de-ducha-a-medida', 'chimeneas-de-marmol'],
  },
  {
    slug: 'fregaderos-de-piedra', chip: 'kitchen', price: null,
    title: 'Fregaderos de piedra a medida integrados en la encimera | ESTONE',
    description: 'Fregaderos de piedra a medida: integrados en la encimera de cuarzo, porcelánico o mármol, sin juntas visibles, con escurridor fresado. Fabricación en Novelda.',
    h1: ['Fregaderos', 'de piedra'],
    sub: 'El fregadero sale de la misma piedra que la encimera: sin juntas, sin contraste, sin suciedad.',
    intro: 'Un fregadero de piedra a medida se fabrica con el mismo material que la encimera, de modo que ambos parecen una sola pieza. Lo montamos bajo encimera o completamente integrado, con las paredes del seno en inglete y el fondo con pendiente hacia el desagüe. Sobre la encimera fresamos un escurridor con ranuras para que el agua vuelva al seno. Fabricamos senos simples, dobles y de gran tamaño en porcelánico, cuarzo, mármol y solid surface.',
    benefits: [
      { t: 'Mismo material', d: 'Fregadero y encimera del mismo color y acabado.' },
      { t: 'Sin rebordes', d: 'Nada donde se acumule la suciedad.' },
      { t: 'Escurridor fresado', d: 'Ranuras en la encimera que vierten al seno.' },
      { t: 'Medida libre', d: 'Seno simple, doble o XL para tu cocina.' },
    ],
    specs: [
      ['Materiales', 'porcelánico, cuarzo, mármol, solid surface'],
      ['Montaje', 'bajo encimera o integrado'],
      ['Senos', 'simple, doble, XL hasta 1000 mm'],
      ['Fondo', 'con pendiente al desagüe'],
      ['Extras', 'escurridor fresado, hueco para grifo'],
    ],
    faq: [
      { q: '¿Un fregadero de mármol es buena idea?', a: 'Es precioso pero exigente: los ácidos lo marcan. Para uso intensivo recomendamos porcelánico o cuarzo.' },
      { q: '¿Se puede integrar un fregadero en mi encimera actual?', a: 'Depende del material y del estado. Normalmente lo hacemos junto con una encimera nueva.' },
      { q: '¿Aguanta el agua caliente?', a: 'Sí. Porcelánico y granito sin problema; en cuarzo evitamos verter agua hirviendo directamente.' },
    ],
    related: ['encimeras-de-cuarzo', 'encimeras-porcelanicas', 'islas-de-cocina'],
  },
  {
    slug: 'islas-de-cocina', chip: 'kitchen', price: 'kitchen',
    title: 'Islas de cocina de piedra con encimera en cascada | ESTONE',
    description: 'Islas de cocina de cuarzo, porcelánico y mármol: encimera de una pieza, laterales en cascada con veta continua, barra y fregadero integrado. A medida en Alicante.',
    h1: ['Islas', 'de cocina'],
    sub: 'Encimera de una pieza y laterales en cascada con la veta continua hasta el suelo.',
    intro: 'La isla es la pieza que más se ve de la cocina, por eso la tratamos como un mueble. Fabricamos la encimera de una sola placa y bajamos los laterales en cascada hasta el suelo con uniones en inglete, para que la veta siga sin cortes. Podemos integrar fregadero, placa de inducción, barra en voladizo para comer y enchufes ocultos. Trabajamos en cuarzo, porcelánico y mármol, y casamos la isla con la encimera de pared.',
    benefits: [
      { t: 'Cascada', d: 'Laterales que bajan hasta el suelo en inglete.' },
      { t: 'Veta continua', d: 'El dibujo sigue de la encimera al lateral.' },
      { t: 'Barra en voladizo', d: 'Zona para comer sin patas a la vista.' },
      { t: 'Todo integrado', d: 'Fregadero, placa y enchufes ocultos.' },
    ],
    specs: [
      ['Materiales', 'cuarzo, porcelánico, mármol'],
      ['Encimera', 'de una pieza hasta 3200 × 1600 mm'],
      ['Laterales', 'cascada en inglete 45°'],
      ['Voladizo barra', 'hasta 300 mm sin refuerzo, más con estructura'],
      ['Integraciones', 'fregadero, inducción, enchufes emergentes'],
    ],
    faq: [
      { q: '¿Qué medida máxima puede tener una isla sin juntas?', a: 'La de la placa: unos 3,2 × 1,6 m. Si es mayor, casamos dos placas con una junta casi invisible.' },
      { q: '¿Aguanta el voladizo de la barra?', a: 'Hasta 30 cm sin refuerzo. Para más, colocamos una estructura de acero oculta.' },
      { q: '¿Podéis hacer solo la isla?', a: 'Sí, aunque recomendamos fabricarla junto con la encimera de pared para que el color coincida.' },
    ],
    related: ['encimeras-de-cocina-a-medida', 'encimeras-de-cuarzo', 'fregaderos-de-piedra'],
  },
  {
    slug: 'chimeneas-de-marmol', chip: 'sculpture', price: null,
    title: 'Chimeneas de mármol y revestimiento de chimeneas en piedra | ESTONE',
    description: 'Chimeneas de mármol a medida: portales clásicos y modernos, revestimiento de chimeneas en porcelánico gran formato y piedra natural. Talla CNC en Novelda.',
    h1: ['Chimeneas', 'de mármol'],
    sub: 'Portales tallados y revestimientos modernos en piedra natural o porcelánico.',
    intro: 'Una chimenea revestida de piedra convierte el salón en otro espacio. Hacemos dos tipos de trabajo: portales de mármol tallados, clásicos o de líneas modernas, que se colocan alrededor del hogar; y revestimientos completos de la pared de la chimenea con mármol o porcelánico gran formato, casi sin juntas y con la veta continua hasta el techo. Modelamos la pieza en 3D, la tallamos con CNC y la instalamos respetando las distancias de seguridad del hogar o insert.',
    benefits: [
      { t: 'Clásica o moderna', d: 'Portales tallados o paredes lisas de piedra.' },
      { t: 'Pared completa', d: 'Revestimiento XXL hasta el techo.' },
      { t: 'Talla CNC', d: 'Molduras y relieves con precisión de taller.' },
      { t: 'Seguridad', d: 'Materiales y distancias aptos para calor.' },
    ],
    specs: [
      ['Materiales', 'mármol, travertino, piedra caliza, porcelánico'],
      ['Tipos', 'portal, revestimiento de pared, repisa'],
      ['Fabricación', 'CNC 5 ejes + acabado a mano'],
      ['Compatible con', 'leña, insert, bioetanol, eléctrica'],
      ['Diseño', 'modelo 3D antes de fabricar'],
    ],
    faq: [
      { q: '¿El mármol aguanta el calor de la chimenea?', a: 'Sí, a las distancias correctas del hogar. Seguimos las indicaciones del fabricante del insert.' },
      { q: '¿Podéis revestir una chimenea existente?', a: 'Sí. Medimos la chimenea actual y fabricamos el revestimiento o portal para ella.' },
      { q: '¿Hacéis diseños a partir de una foto?', a: 'Sí. Nos mandas la referencia, la adaptamos a tus medidas y te enseñamos el modelo 3D.' },
    ],
    related: ['porcelanico-gran-formato', 'esculturas-de-marmol', 'mesas-de-marmol'],
  },
  {
    slug: 'corte-por-chorro-de-agua', chip: 'waterjet', price: 'waterjet',
    title: 'Corte por chorro de agua (waterjet) en Alicante | Piedra, vidrio, metal',
    description: 'Servicio de corte por chorro de agua en Novelda, Alicante: piedra, porcelánico, vidrio, metal y más. Marquetería, logotipos, piezas a plano DXF. Particulares y empresas.',
    h1: ['Corte por', 'chorro de agua'],
    sub: 'Waterjet para formas que una sierra no puede hacer. Tu material o el nuestro.',
    intro: 'El corte por chorro de agua usa agua a muy alta presión mezclada con abrasivo para cortar casi cualquier material sin calentarlo ni astillarlo. Por eso es la técnica para formas complejas: marquetería e incrustaciones en suelos, logotipos, rosetones, piezas curvas y huecos precisos en porcelánico. Ofrecemos el servicio a particulares, marmolerías, carpinterías, cerrajerías e interioristas: nos mandas el plano en DXF o DWG, o lo dibujamos nosotros a partir de un boceto.',
    benefits: [
      { t: 'Sin calor', d: 'No deforma ni cambia el material.' },
      { t: 'Cualquier forma', d: 'Curvas, calados e interiores cerrados.' },
      { t: 'Muchos materiales', d: 'Piedra, porcelánico, vidrio, metal, goma.' },
      { t: 'A plano', d: 'Trabajamos con DXF, DWG o PDF acotado.' },
    ],
    specs: [
      ['Materiales', 'piedra, porcelánico, vidrio, acero, aluminio, latón'],
      ['Formatos de archivo', 'DXF, DWG, PDF acotado'],
      ['Mesa de corte', 'medidas bajo consulta'],
      ['Grosor máximo', 'según material, bajo consulta'],
      ['Clientes', 'particulares y profesionales'],
    ],
    faq: [
      { q: '¿Puedo llevar mi propio material?', a: 'Sí. Revisamos la placa y te damos precio por metro de corte y por perforación.' },
      { q: '¿Necesito un plano en DXF?', a: 'Es lo ideal. Si no lo tienes, lo dibujamos nosotros a partir de un boceto acotado.' },
      { q: '¿Hacéis series para empresas?', a: 'Sí, con tarifa profesional y plazos fijos.' },
    ],
    related: ['corte-de-piedra-a-medida', 'esculturas-de-marmol', 'porcelanico-gran-formato'],
  },
  {
    slug: 'corte-de-piedra-a-medida', chip: 'cutting', price: 'cutting',
    title: 'Corte de mármol y piedra a medida en Alicante | Taller en Novelda',
    description: 'Corte de mármol, granito, cuarzo y porcelánico a medida: encimeras, huecos, ingletes, cantos y pulido. Para particulares, cocinas, carpinterías y marmolerías.',
    h1: ['Corte de piedra', 'a medida'],
    sub: 'Cortamos, perfilamos y pulimos placas de mármol, granito, cuarzo y porcelánico.',
    intro: 'Si tienes la placa pero no la maquinaria, nosotros cortamos por ti. Hacemos corte recto e inglete con puente de corte, huecos de placa y fregadero por CNC, cantos perfilados y pulido. Trabajamos para particulares que compran su material, para tiendas de cocina que necesitan encimeras terminadas y para otras marmolerías con picos de trabajo. Recibimos planos en DWG o DXF, o medimos nosotros en obra.',
    benefits: [
      { t: 'Para profesionales', d: 'Cocinas, carpinterías y marmolerías.' },
      { t: 'Tu placa o la nuestra', d: 'Revisamos el material antes de cortar.' },
      { t: 'Terminado completo', d: 'Corte, huecos, cantos y pulido.' },
      { t: 'Plazos fijos', d: 'Fecha de entrega cerrada al aceptar.' },
    ],
    specs: [
      ['Materiales', 'mármol, granito, cuarzo, porcelánico, sinterizado'],
      ['Operaciones', 'corte recto, inglete 45°, huecos, cantos, pulido'],
      ['Maquinaria', 'puente de corte, CNC, waterjet'],
      ['Planos', 'DWG, DXF, PDF acotado o medición en obra'],
      ['Entrega', 'recogida en taller o transporte'],
    ],
    faq: [
      { q: '¿Cortáis encimeras compradas en otra tienda?', a: 'Sí. Nos traes la placa, cortamos huecos y cantos, y si quieres la instalamos.' },
      { q: '¿Cómo se calcula el precio?', a: 'Por metro lineal de corte, por hueco y por metro de canto pulido. Te damos presupuesto cerrado antes de empezar.' },
      { q: '¿Tenéis tarifa para profesionales?', a: 'Sí, para cocinas, carpinterías y marmolerías con trabajo recurrente.' },
    ],
    related: ['corte-por-chorro-de-agua', 'encimeras-de-cocina-a-medida', 'marmoleria-alicante'],
  },
  {
    slug: 'esculturas-de-marmol', chip: 'sculpture', price: 'sculpture',
    title: 'Esculturas de mármol modernas a medida | Talla CNC y a mano | ESTONE',
    description: 'Esculturas de mármol modernas para interior y jardín: formas abstractas y orgánicas, relieves, fuentes y piezas de autor. Modelado 3D, talla CNC y acabado a mano en Novelda.',
    h1: ['Esculturas', 'de mármol'],
    sub: 'Piezas contemporáneas para casa, jardín y espacios públicos, talladas en Novelda.',
    intro: 'Hacemos esculturas de mármol contemporáneas: formas abstractas y orgánicas, volúmenes geométricos, relieves murales y fuentes. El proceso une tecnología y oficio: modelamos la pieza en 3D contigo o con tu artista, la desbastamos con CNC de 5 ejes y la terminamos a mano, con zonas pulidas, apomazadas o en bruto. Trabajamos también a partir de modelos existentes, escaneos o bocetos, para particulares, interioristas, hoteles y artistas que necesitan un taller.',
    benefits: [
      { t: 'Diseño contemporáneo', d: 'Formas abstractas, orgánicas y geométricas.' },
      { t: '3D antes de tallar', d: 'Ves la pieza antes de empezar el bloque.' },
      { t: 'CNC + mano', d: 'Precisión de máquina y acabado de taller.' },
      { t: 'Taller para artistas', d: 'Ejecutamos piezas de autor a partir de tu modelo.' },
    ],
    specs: [
      ['Materiales', 'mármol blanco, negro, travertino, ónix, caliza'],
      ['Tamaño', 'de objeto de mesa a pieza monumental'],
      ['Proceso', 'modelo 3D → CNC 5 ejes → acabado a mano'],
      ['Acabados', 'pulido, apomazado, abujardado, en bruto'],
      ['Uso', 'interior, jardín, fachada, espacio público'],
    ],
    faq: [
      { q: '¿Podéis tallar una escultura a partir de mi diseño?', a: 'Sí. Nos mandas un boceto, un modelo 3D o una maqueta y lo adaptamos al bloque.' },
      { q: '¿El mármol aguanta en el jardín?', a: 'Sí, eligiendo la piedra adecuada. Algunos mármoles envejecen con la lluvia; te aconsejamos cuál usar.' },
      { q: '¿Cuánto tarda una escultura?', a: 'Depende del tamaño y del detalle: desde unas semanas para piezas medianas. Te damos el plazo con el presupuesto.' },
    ],
    related: ['chimeneas-de-marmol', 'mesas-de-marmol', 'lavabos-de-piedra'],
  },
  {
    slug: 'fachadas-ventiladas', chip: 'cladding', price: null,
    title: 'Fachada ventilada de porcelánico y piedra en Alicante | ESTONE',
    description: 'Fachadas ventiladas de porcelánico gran formato y piedra natural para viviendas y edificios. Cortado a plano, anclajes ocultos, suministro y montaje en la Costa Blanca.',
    h1: ['Fachadas', 'ventiladas'],
    sub: 'Porcelánico gran formato y piedra natural cortados a plano para tu fachada.',
    intro: 'Una fachada ventilada separa el revestimiento del muro con una cámara de aire: la casa gana aislamiento, la humedad no pasa y el acabado dura décadas sin mantenimiento. Cortamos el porcelánico de gran formato o la piedra natural según el despiece de tu proyecto, con los mecanizados para anclajes ocultos o vistos, y coordinamos el montaje con tu constructora o con nuestro equipo. Trabajamos para viviendas unifamiliares, reformas y promociones.',
    benefits: [
      { t: 'Aislamiento', d: 'La cámara de aire mejora el comportamiento térmico.' },
      { t: 'Sin mantenimiento', d: 'Porcelánico que no se decolora con el sol.' },
      { t: 'Cortado a plano', d: 'Despiece y mecanizados desde tu proyecto.' },
      { t: 'Para promotoras', d: 'Plazos y suministro por fases de obra.' },
    ],
    specs: [
      ['Materiales', 'porcelánico 12–20 mm, piedra natural 20–30 mm'],
      ['Formato', 'hasta 3200 × 1600 mm'],
      ['Anclajes', 'ocultos (ranura o taladro) o vistos'],
      ['Documentación', 'despiece a partir de DWG'],
      ['Clientes', 'particulares, arquitectos, constructoras'],
    ],
    faq: [
      { q: '¿Cuánto cuesta una fachada ventilada?', a: 'Depende del material, la subestructura y la altura. Con los planos te damos un presupuesto por metro cuadrado.' },
      { q: '¿Suministráis solo el material cortado?', a: 'Sí, podemos entregar las placas mecanizadas para que las monte tu equipo.' },
      { q: '¿Qué ventaja tiene frente a un enfoscado?', a: 'Más aislamiento, sin grietas ni pintura cada pocos años y un acabado de gran formato.' },
    ],
    related: ['porcelanico-gran-formato', 'corte-de-piedra-a-medida', 'corte-por-chorro-de-agua'],
  },
  {
    slug: 'marmoleria-alicante', chip: 'other', price: null,
    title: 'Marmolería en Alicante: taller propio en Novelda | ESTONE',
    description: 'Marmolería en la provincia de Alicante con taller propio en Novelda: encimeras, baños, escaleras, mesas, chimeneas y corte waterjet. Medición e instalación en la Costa Blanca.',
    h1: ['Marmolería', 'en Alicante'],
    sub: 'Taller propio en Novelda. Medimos, fabricamos e instalamos en toda la provincia.',
    intro: 'Somos una marmolería con taller propio en L\'Estació de Novelda, en el corazón de la industria del mármol de Alicante. Fabricamos encimeras de cocina y baño, lavabos, platos de ducha, escaleras, revestimientos, mesas, chimeneas y esculturas, y ofrecemos corte a medida y por chorro de agua para profesionales. Llevamos 14 años trabajando la piedra y atendemos en español, inglés, ruso y ucraniano. Puedes visitarnos con cita para ver placas y trabajos.',
    benefits: [
      { t: 'Taller en Novelda', d: 'A menos de 30 minutos de Alicante y Elche.' },
      { t: 'Todo en piedra', d: 'Cocina, baño, escaleras, mobiliario y arte.' },
      { t: 'Equipo propio', d: 'Medición e instalación sin subcontratas.' },
      { t: 'Cuatro idiomas', d: 'Español, inglés, ruso y ucraniano.' },
    ],
    specs: [
      ['Dirección', 'L\'Estació de Novelda, 03660 Novelda'],
      ['Horario', 'lunes a viernes, 8:00–18:00'],
      ['Visitas', 'con cita previa'],
      ['Zona de trabajo', 'provincia de Alicante; Murcia y Valencia bajo consulta'],
      ['Materiales', 'mármol, granito, cuarzo, porcelánico, solid surface'],
    ],
    faq: [
      { q: '¿Dónde está vuestro taller?', a: 'En L\'Estació de Novelda (Alicante). Pide cita por teléfono o WhatsApp antes de venir.' },
      { q: '¿Hacéis desplazamientos a la costa?', a: 'Sí: Alicante, Elche, Benidorm, Altea, Calpe, Jávea, Dénia, Torrevieja, Orihuela y alrededores.' },
      { q: '¿Cuánto tardáis en dar presupuesto?', a: 'Con medidas aproximadas o fotos, en 24 horas. Tras la medición, presupuesto cerrado.' },
    ],
    related: ['encimeras-de-cocina-a-medida', 'escaleras-de-marmol', 'corte-de-piedra-a-medida'],
  },
];
